"""Add Rack model and expand Device model for STB management

Revision ID: 66a0812bb5eb
Revises: 732b0ff2af4c
Create Date: 2026-02-04 23:07:49.764661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a0812bb5eb'
down_revision: Union[str, None] = '732b0ff2af4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create racks table
    op.create_table('racks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_racks_id'), 'racks', ['id'], unique=False)
    op.create_index(op.f('ix_racks_name'), 'racks', ['name'], unique=True)
    
    # Step 2: Migrate existing rack_name data to racks table (if devices table exists)
    # Get database connection
    conn = op.get_bind()
    
    # Check if devices table exists before trying to migrate data
    inspector = sa.inspect(conn)
    if 'devices' in inspector.get_table_names():
        # Get unique rack names from devices
        result = conn.execute(sa.text("SELECT DISTINCT rack_name FROM devices WHERE rack_name IS NOT NULL"))
        rack_names = [row[0] for row in result]
        
        # Insert unique racks
        for rack_name in rack_names:
            conn.execute(
                sa.text("INSERT INTO racks (name) VALUES (:name)"),
                {"name": rack_name}
            )
    
    # Step 3: SQLite doesn't support ALTER COLUMN, so we need to use batch operations
    # Add all new device columns in one batch
    with op.batch_alter_table('devices', schema=None) as batch_op:
        # Add rack_id temporarily nullable
        batch_op.add_column(sa.Column('rack_id', sa.Integer(), nullable=True))
        # Add all other columns
        batch_op.add_column(sa.Column('make', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model_alias', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('firmware', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('host_mac', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('host_ipv4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('host_ipv6', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('control_uris', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('external_equipment', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('state_changed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('allocation_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('software_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_verified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Step 4: Populate rack_id based on rack_name
    conn.execute(sa.text("""
        UPDATE devices 
        SET rack_id = (SELECT id FROM racks WHERE racks.name = devices.rack_name)
    """))
    
    # Step 5: For SQLite, we need to recreate the table to make rack_id NOT NULL
    # This is done via batch operations which recreates the table
    with op.batch_alter_table('devices', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('rack_id', nullable=False, existing_type=sa.Integer())
        batch_op.alter_column('state', nullable=False, existing_type=sa.String())
        batch_op.create_index('ix_device_state_rack', ['state', 'rack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_rack_id'), ['rack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_state'), ['state'], unique=False)
        batch_op.create_unique_constraint('uix_rack_slot', ['rack_id', 'slot_name'])
        batch_op.create_foreign_key('fk_devices_rack', 'racks', ['rack_id'], ['id'])
        batch_op.drop_column('rack_name')
    
    # Step 6: Update allocation_history columns
    op.add_column('allocation_history', sa.Column('duration_requested', sa.Integer(), nullable=True))
    op.add_column('allocation_history', sa.Column('state_before', sa.String(), nullable=True))
    op.add_column('allocation_history', sa.Column('state_after', sa.String(), nullable=True))
    op.add_column('allocation_history', sa.Column('software_version', sa.String(), nullable=True))
    
    with op.batch_alter_table('allocation_history', schema=None) as batch_op:
        batch_op.alter_column('device_id', nullable=False, existing_type=sa.INTEGER())
        batch_op.alter_column('email', nullable=False, existing_type=sa.VARCHAR())
        batch_op.alter_column('start_time', nullable=False, existing_type=sa.DATETIME())
        batch_op.create_index(batch_op.f('ix_allocation_history_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_history_email'), ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('rack_name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint('uix_rack_slot', 'devices', type_='unique')
    op.drop_index(op.f('ix_devices_state'), table_name='devices')
    op.drop_index(op.f('ix_devices_rack_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_platform'), table_name='devices')
    op.drop_index(op.f('ix_devices_owner_email'), table_name='devices')
    op.drop_index('ix_device_state_rack', table_name='devices')
    op.alter_column('devices', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'created_at')
    op.drop_column('devices', 'last_verified')
    op.drop_column('devices', 'software_version')
    op.drop_column('devices', 'allocation_expiry')
    op.drop_column('devices', 'state_changed_at')
    op.drop_column('devices', 'external_equipment')
    op.drop_column('devices', 'control_uris')
    op.drop_column('devices', 'host_ipv6')
    op.drop_column('devices', 'host_ipv4')
    op.drop_column('devices', 'host_mac')
    op.drop_column('devices', 'firmware')
    op.drop_column('devices', 'manufacturer')
    op.drop_column('devices', 'serial_number')
    op.drop_column('devices', 'model_alias')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'make')
    op.drop_column('devices', 'rack_id')
    op.drop_index(op.f('ix_allocation_history_email'), table_name='allocation_history')
    op.drop_index(op.f('ix_allocation_history_device_id'), table_name='allocation_history')
    op.alter_column('allocation_history', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('allocation_history', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('allocation_history', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('allocation_history', 'software_version')
    op.drop_column('allocation_history', 'state_after')
    op.drop_column('allocation_history', 'state_before')
    op.drop_column('allocation_history', 'duration_requested')
    op.drop_index(op.f('ix_racks_name'), table_name='racks')
    op.drop_index(op.f('ix_racks_id'), table_name='racks')
    op.drop_table('racks')
    # ### end Alembic commands ###
