"""Add TestExecution table and complete phase 2 features

Revision ID: 755c75b1348e
Revises: 66a0812bb5eb
Create Date: 2026-02-06 19:39:17.318321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755c75b1348e'
down_revision: Union[str, None] = '66a0812bb5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
